version: '3.8'

services:
  node-server:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - ./server.js:/app/server.js
  postgres-db:
    image: postgres:latest
    container_name: my_postgres_container_name
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  volumes:
    postgres_data:
